### ISSUE TITLE
[Feature Request] Log staff chat in separate file.

### ISSUE THREAD

**Issue by BiGUNMAN** [WoutDev/BungeeStaffChat#13]
It would be awesome to see a feature where staff chat could be logged in a separate file in the bungeestaffchat directory. I'll gladly send you a couple $ if you can implement this asap. :)

**Comment by WoutDev** [comment]
No need for money, I'll implement this after my exams are finished (in a few days). :+1:

**Comment by WoutDev** [comment]
Feature has been added in the latest release, 2.0.0!
