### ISSUE TITLE
Be able to customize /gr messages.

### ISSUE THREAD

**Issue by mibby** [WoutDev/BungeeStaffChat#9]
BungeeStaffChat 1.5.4

I'd like to be able to customize the language of /gr (quick replying to cross server pms). More specifically, these messages.

https://github.com/WoutDev/BungeeStaffChat/commit/c1cbb004dcf453bf67ffcc24d14779a30d6061ed#diff-03cc8cea5e8899f67236ea519a5a0852R24
pp.sendMessage(ChatColor.RED + "Please specify message!");
pp.sendMessage(ChatColor.RED + "Your receiver is offline!"
pp.sendMessage(ChatColor.RED + "You can't reply because nobody sended you a message before!");
sender.sendMessage("You can't quick reply as console!");

The language file does not seem to have lines to be able to customize them.

**Comment by WoutDev** [comment]
Due motivation reasons I was inactive for a very, very long time. I have now tried to implement the feature. It's a bad practice to commit code before testing it completely, but I really wanted to get that through today. I'm going to test the whole 1.6.0 version before releasing it on Spigot.
